### ISSUE TITLE
Automatic Column Switching for Alta CV Sections

### ISSUE THREAD

**Issue by mahfuzullah** [liantze/AltaCV#105]
Currently, when creating multi-column documents using Alta CV, there is a need to manually insert a "\switchcolumn" command to switch the content to the next column once a section reaches the end of the page.  i was looking for a way to continue my text in the next column instead of next page automatically. also why was this implemented this way ?

**Comment by AlbertoFabbri93** [comment]
I like the way it is currently implemented, it lets us choose what we want in each column.

**Comment by mahfuzullah** [comment]
> I like the way it is currently implemented, it lets us choose what we want in each column.

understable, i will mark this as closed

**Comment by liantze** [comment]
You can load the `multicol` package i.e. `\begin{multicols}{2}...\end{multicols}` instead of `paracacol`. 

But the columns created with `multicols` always have equal width: this is exactly why `paracol` was used in the template. And as @AlbertoFabbri93 remarked, perhaps more flexible since you can decide where to use `\switchcolumn`.

Also note that `paracol` is loaded in the `.tex`, not in the `.cls`, and the `.tex` example uses `\begin{paracol}{2}...\end{paracol}` instead of a custom environment name defined in the `.cls`. I did this on purpose, so that authors are certainly not forced/limited to use the `paracol` package or environment. You can use `multicols`, `minipage`, `adjustwidth` etc (or no environments at all to just use a single full text-width column!) to implement their own preferred layout.
