### ISSUE TITLE
Backward compatibility broken: please clarify by tagging, README or make \mynames optional

### ISSUE THREAD

**Issue by JosjaVanBever** [liantze/AltaCV#117]
This issue is related to  #116 but not exactly the same.

Compilation with
lualatex sample.tex
works till commit 81a2b47d160976e4efccd93402eaf36c1985537a

Starting from commit 483e6a60e218589cef65cab5e760e69f2718eacd
v1.6.5 Adds \mynames for specifying names to highlight in the publication list
backward compatibility with texlive distributions from apt in ubuntu 20 LTS is broken.

Possible relevant output of apt (no newer versions on apt, ubuntu 20 LTS):
texlive-luatex/focal,focal,now 2019.20200218-1 all [installed,automatic]

I suggest to tag commit 81a2b47d160976e4efccd93402eaf36c1985537a as "Backward compatible" and add a warning add the beginning of the README stating "Older versions of Texlive (apt on Ubuntu 20 LTS ...) are required to checkout the tag "Backward compatible" and use lualatex instead."

In a second stage I would suggest to fix the backward compatibility issue by taking a look at the \mynames command or make it somehow optional.

**Comment by liantze** [comment]
Commit https://github.com/liantze/AltaCV/commit/f1c41cf9b70968100e30c6a132e6e4813d3f6d33 should now address most of these backward incompatibilities (I was hoping to get away with them...), at least for the following

- LaTeX `2020-10-01` introduced hooks management mechanisms, so `\AddToHook{begindocument/before}` was favored over `\AtBeginDocument`. And `\AddToHookPackage{package/<name>/after}` (since `2021-11-15`) was favored over `scrlfile`'s `\AfterPackage`.
- `\faOrcid` became available in `fontawesome5` v5.12.0 so that was favored over `\aiOrcid` from `academicons` (which requires XeLaTeX or LuaLaTeX) previously
- (This is more recent) The new X icon is only available via `simpleicons` v9.9.0

https://github.com/liantze/AltaCV/commit/f1c41cf9b70968100e30c6a132e6e4813d3f6d33 should now fall back to use `\AtBeginDocument`, `\AfterPackage`, `\aiOrcid`, `\faTwitter` if the new commands/mechanisms aren't available.
