### ISSUE TITLE
Skype Icon to the top bar as a contact

### ISSUE THREAD

**Issue by G-Pereira** [liantze/AltaCV#25]
Tittle says it all :) just and enhancement. I love this work!

**Comment by liantze** [comment]
(See also #4 )

You can use `\personalinfo{...,\printinfo{\faSkype}{foobar},...}` to add Skype (or any other platforms/symbols you like). As mentioned in #4, I've decided against providing further explicit commands for services/platforms because there are so. many. worldwide, and I'm sure more will be born everyday! :-)
