### ISSUE TITLE
Multiple translations

### ISSUE THREAD

**Issue by radiegues06** [liantze/AltaCV#50]
Hi! Thanks for the repo! I really liked the CV template.

I would like to suggest support for multi language texts: I would like an ease way to translate my CV into other languages without having to create another file.

Please, check this link, where I have found a simple solution: https://tex.stackexchange.com/questions/60781/managing-multiple-translation-of-a-single-document.

I have added the following code to the `altacv.cls` file so I could select the language to which I want to compile the project.

```
\newif\ifen
\newif\ifpt

\newcommand{\en}[1]{\ifen#1\fi}
\newcommand{\pt}[1]{\ifpt#1\fi}
```

Then, I can select the language to use, depending on the line that is not commented, as follows:
```
%\entrue
\pttrue
```

I can then use on my text, for example:
`\tagline{\en{Aeronautical Engineer} \pt{Engenheiro Aeronáutico}}`

I tried to make something similar to what you already have, but I unfortunately coudn't.

So, I think it would be a really nice functionality to have.

Thank you!

**Comment by liantze** [comment]
You can add these in the preamble of the .tex file itself; it's not necessary to put them in the .cls file. (If we did then the .cls would need to ideally support more languages, which is not really feasible!)

AltaCV was never created to be the end-all CV template :-) and that was why I left some settings, including the page margins, the font choices etc to be done in the .tex preamble itself, rather than the .cls file.

**Comment by liantze** [comment]
Also, adding too many if/else toggles might just be too risky with extra/missing braces later on i.e. getting too hairy to debug if you run into compile errors... Perhaps OmegaT might help make translating your .tex file easier i.e. make the workflow to produce a separate .tex file with the same LaTeX structure, but in a different language, easier? https://tex.stackexchange.com/a/369288/226

**Comment by radiegues06** [comment]
I understand. Thank you for your time, great work!
