### ISSUE TITLE
datetime package

### ISSUE THREAD

**Issue by shahram7** [liantze/AltaCV#58]
Hi,
first I thank you for everything you have done so far for AltaCV.
i would like to add date in german format at the end of my CV.
so i've added this lines after \documentclass:
```
\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}
\usepackage[ngerman]{babel}
\usepackage{datetime}

```
now it should be good but it doesn't work .

`Berlin,  den \date{\today}
`
I would be grateful if someone can help me.

**Comment by liantze** [comment]
`\date{\today}` won't output anything, because it's just saving a string into another variable `\@date` for later use (e.g. by `\maketitle`. So you just need to write `Berlin, den \today`.

Note also that `datetime` is now obsolete, so you might want to replace `\usepackage{datetime}` with `\usepackage[useregional]{datetime2}`.
