### ISSUE TITLE
Impossible to customize bibliography style

### ISSUE THREAD

**Issue by Mar-Veloz** [liantze/AltaCV#71]
The bibliography style is hard-coded as `authoryear` in the class definition when biblatex is loaded, which makes it impossible to use a different bibliography style.

**Comment by liantze** [comment]
Hmm, good point. Though I'm wondering if we want to allow using a different biblatex style, then perhaps things should be re-organised by moving out all the biblatex-related code, including custom to separate .tex files (apastyle-publist.tex; chicago-publist.tex etc) that users can modify directly, or swap out entire .tex files. Otherwise some existing customisations (e.g. the `\AtEveryBibitem` to insert the bullet points) doesn't work well with numeric styles e.g. `style=ieee`.
