### ISSUE TITLE
ATS friendly?

### ISSUE THREAD

**Issue by harsham05** [liantze/AltaCV#76]
@liantze Is AltaCV Applicant Tracking System friendly?

**Comment by marcusfechner** [comment]
I think the question depends on the ATS system used by the company.

There are several websites were you can parse your resume and check if an ATS finds the correct information from your resume. 
(But don't use their services, which are overpriced, etc.. They just wanna scam you in using their services.)
Here are some links:
- https://www.jobscan.co/
- https://resumeworded.com/
- https://skillsyncer.com/


Generally the PDF will be parsed to a text file first and then it will be processed by the ATS system.
You can check the output of your PDF as a text here: https://pdftotext.com/

From my experience the information from the resume can be parsed, but the order is messed up.
So instead of reading the left column and then the right. It will read blocks from the left column, then from the right and again from the left, and so on. I hope I could somehow illustrate it below.

PDF:                  Text Output
----------           -----
| L1   R1 |           | L1 |
| L2   R2 | ---->  | R1 |           
| L3   R3 |           | L2 |           
----------           | R2 |
                          | ...  |           
                          -----
                          
However, the order of bullet points, text blocks is preserved and words are not scrambled.
As order should not matter that much for an ATS system, it should pass the ATS.

I hope I could clarify some of your concerns.

**Comment by liantze** [comment]
Thanks @marcusfechner . Interestingly [`pdftotext -layout sample.pdf`](https://www.tutorialspoint.com/unix_commands/pdftotext.htm) can produce a .txt that roughly mimics the two-columnar layout (that is, if you used `paracol` in the .tex).

Perhaps with the help of the `accsupp` help package, the icons in `\personalinfo` and the scores in `\cvskill` can have "copyable" plain text that would make more sense for `pdftotext` and similar utilities.
