### ISSUE TITLE
How do I swap columns?

### ISSUE THREAD

**Issue by TheEnlightened1** [liantze/AltaCV#96]
Hi folks 

I've got a very nearly complete template, spacing/sizing of everything is perfect. All I want to do is simply swap the columns, so "My philosophy" quote and everything else on the right goes over to the left. 

I see the issue was raised in #19 which I have tried, but it doesn't swap and just jams everything over to the right. 

Any help appreciated

**Comment by liantze** [comment]
#19 works only for an old, old version of `altacv.cls` and `legacy/sample-old.tex`.

If you are using the current version of the template i.e. your .tex file has `\begin{paracol}{2}...\end{paracol}`, then change the column ratio from `\columnratio{0.6}` to `\columnratio{0.4}` so that the left column : right column ratio is 4 : 6.

Then write `\cvsection{My phillosophy}` etc immediately after `\begin{paracol}{2}`, and move `\cvsection{Experience}` etc to after the `\swichcolumn`. See the comments in `sample.tex` for guidance.
